# Generated by Django 2.2 on 2020-08-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poll',
            new_name='Quiz',
        ),
    ]
