# Generated by Django 2.2 on 2020-08-29 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200829_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collecting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collecting_answer', to='webapp.Answer', verbose_name='Вопрос')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collecting_quiz', to='webapp.Quiz', verbose_name='Вопрос')),
            ],
        ),
    ]
